### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Reikooters** [drachtio/ansible-role-fsmrf#7]
Hi there

I'm new to Freeswitch and have been playing around with it recently. I saw your repository https://github.com/davehorton/drachtio-freeswitch-modules and wanted to try it out, which lead me to this repository.

How would I install this? I have never used ansible before.

I did a bit of googling and here is what I tried.

I have a clean install of Debian 10.
I installed ansible as per below:

```
sudo apt update
sudo apt install ansible -y
```

I saw you posted this playbook on this issue (https://github.com/davehorton/ansible-role-fsmrf/issues/6), which appears to be more current than the one on the readme:

```
---
- hosts: all
  become: yes
  vars_prompt:
    - name: "build_with_extra"
      prompt: "Include the extra modules (mod_aws_transcribe, mod_google_transcribe, mod_google_tts, mod_dialogflow)?"
      private: no
      default: false
    - name: "cloud_provider"
      prompt: "Cloud provider: aws, gcp, azure, digital_ocean"
      private: no
      default: none

  roles:
    - ansible-role-fsmrf
```

I created a file with the above content called install.yml in the root directory of where I extracted the files to, and tried the following command (found online for running a playbook locally)

`ansible-playbook -c local -i localhost, install.yml`

But I got the following error:

```
ERROR! the role 'ansible-role-fsmrf' was not found in /root/ansible-role-fsmrf-master/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root/ansible-role-fsmrf-master

The error appears to have been in '/root/ansible-role-fsmrf-master/install.yml': line 15, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-role-fsmrf
      ^ here
```

I noticed there is no roles folder in the repository. Should this file be in a specific folder, is there another file I need to create, or am I way off?

Any guidance would be appreciated.
